package au.org.ala.biocache

object AssertionCodes {

	val GEOSPATIAL_PRESUMED_NEGATED_LATITUDE = 1;
	val GEOSPATIAL_PRESUMED_NEGATED_LONGITUDE = 2;
	val GEOSPATIAL_PRESUMED_INVERTED_COORDINATES = 3;
	val GEOSPATIAL_ZERO_COORDINATES = 4;
	val GEOSPATIAL_COORDINATES_OUT_OF_RANGE = 5;
	val GEOSPATIAL_COUNTRY_COORDINATE_MISMATCH = 6;
	val GEOSPATIAL_UNKNOWN_COUNTRY_NAME = 7;
	val GEOSPATIAL_ALTITUDE_OUT_OF_RANGE = 8;
	val GEOSPATIAL_PRESUMED_ERRONOUS_ALTITUDE = 9;
	val GEOSPATIAL_PRESUMED_MIN_MAX_ALTITUDE_REVERSED = 0x200;
	val GEOSPATIAL_PRESUMED_DEPTH_IN_FEET = 0x400;
	val GEOSPATIAL_DEPTH_OUT_OF_RANGE = 0x800;
	val GEOSPATIAL_PRESUMED_MIN_MAX_DEPTH_REVERSED = 0x1000;
	val GEOSPATIAL_PRESUMED_ALTITUDE_IN_FEET = 0x2000;
	val GEOSPATIAL_PRESUMED_ALTITUDE_NON_NUMERIC = 0x4000;
	val GEOSPATIAL_PRESUMED_DEPTH_NON_NUMERIC = 0x8000;

	val TAXONOMIC_INVALID_SCIENTIFIC_NAME = 0x01;
	val TAXONOMIC_UNKNOWN_KINGDOM = 0x02;
	val TAXONOMIC_AMBIGUOUS_NAME = 0x04;

	val OTHER_MISSING_CATALOGUE_NUMBER = 0x01;
	val OTHER_MISSING_BASIS_OF_RECORD = 0x02;
	val OTHER_INVALID_DATE = 0x04;
	val OTHER_COUNTRY_INFERRED_FROM_COORDINATES = 0x08;
}